apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-webapp-svc
  #namespace: pj-1-ns
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-webapp-svc
            port:
              number: 31007 # it is a node port bcz service resides inside the k8s

