apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: pj-1-ns
---
#apiVersion: rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: training-role
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: pj-1-ns
